import { defaultPlayer, playerReducer } from './player';
import type { GameResult } from '../game/types';
export const completion: GameResult = { mode: 'level', levelId: 'en-easy', locale: 'en', puzzleRevision: 1, id: 'first', sessionId: 'test', outcome: 'won', mistakes: 1, hintsUsed: 0, elapsedMs: 1000, completedAt: '2026-09-17T12:00:00Z' };
test('preferences are immutable and independent', () => { const s = defaultPlayer(); expect(playerReducer(s, { type: 'preferences', value: { language: 'fr' } }).preferences.language).toBe('fr'); expect(s.preferences.language).toBe('system'); });
test('win completes only concrete locale puzzle and deduplicates', () => { const s = playerReducer(defaultPlayer(), { type: 'complete', result: completion }); expect(s.completedLevels).toEqual(['en-easy']); expect(playerReducer(s, { type: 'complete', result: completion })).toBe(s); });
test('loss records result without advancing progress', () => { const s = playerReducer(defaultPlayer(), { type: 'complete', result: { ...completion, outcome: 'lost', mistakes: 4 } }); expect(s.completedLevels).toEqual([]); expect(s.lastResult?.outcome).toBe('lost'); });
test('daily win survives losing replay and stays isolated by locale', () => { const r: GameResult = { ...completion, mode: 'daily', date: '2026-09-17' }; const s = playerReducer(defaultPlayer(), { type: 'complete', result: r }); const next = playerReducer(s, { type: 'complete', result: { ...r, id: 'second', outcome: 'lost', mistakes: 4 } }); expect(next.dailyCompletions['en:2026-09-17']).toEqual(r); expect(next.completedLevels).toEqual([]); expect(next.dailyCompletions['fr:2026-09-17']).toBeUndefined(); });
test('reset preserves preferences', () => { const s = playerReducer(defaultPlayer(), { type: 'complete', result: completion }); expect(playerReducer(s, { type: 'resetProgress' })).toEqual(defaultPlayer()); });
test.each([NaN, Infinity, -1])('invalid elapsed time %s rejected', elapsedMs => { const s = defaultPlayer(); expect(playerReducer(s, { type: 'complete', result: { ...completion, elapsedMs } })).toBe(s); });
